### ISSUE TITLE
可以直连，跳过注册中心么

### ISSUE THREAD

**Issue by ly0** [QianmiOpen/dubbo-client-py#1]
如题。

**Comment by JoeCao** [comment]
目前支持两种注册，Multicast组播和Zookeeper注册中心。
如果需要直连，可以直接使用JsonRPC的Python客户端。或者继承Registry对象，只需要实现一个接口get_provides的时候返回固定的ip_port和serviceurl

**Comment by ly0** [comment]
我刚刚想直接写serviceurl来着  可是却不知道是神马，提供者只提供了一个ip和port

**Comment by JoeCao** [comment]
service_url类似如下
jsonrpc://192.168.2.1:38080/com.ofpay.demo.api.UserProvider?
        anyhost=true&application=demo-provider&default.timeout=10000&dubbo=2.4.10&
        environment=product&interface=com.ofpay.demo.api.UserProvider&
        methods=getUser,queryAll,queryUser,isLimit&owner=wenwu&pid=61578&
        side=provider&timestamp=1428904600188
这个url的解析是在common.py的ServiceURL对象中的
其中问号之前的com.ofpay.demo.api.UserProvider这个path最关键
因为后续构造httpclient需要使用到它。你试试看

**Comment by JoeCao** [comment]
另外，记得将dubbo服务端配置加上jsonrpc的支持，这样我们就可以略过烦人的hessian协议
https://github.com/QianmiOpen/dubbo-rpc-jsonrpc

**Comment by ly0** [comment]
TAT 伤心，他们用的真的是 hessian 协议

**Comment by JoeCao** [comment]
no more future information. close it.
